sudo: false

dist: bionic

language:
    - c++

# Blacklist
branches:
  only:
    - master

# Install dependencies
addons:
  apt:
    packages:
      - doxygen
      - graphviz
      - libboost-dev

install:
  - mkdir ${TRAVIS_BUILD_DIR}/deps
  - wget https://cmake.org/files/v3.16/cmake-3.16.2-Linux-x86_64.sh
  - sh cmake-3.16.2-Linux-x86_64.sh --prefix=${TRAVIS_BUILD_DIR}/deps/cmake --exclude-subdir
  - PATH=${TRAVIS_BUILD_DIR}/deps/cmake:${TRAVIS_BUILD_DIR}/deps/cmake/bin:$PATH

# Build your code e.g. by calling make
script:
  - mkdir build && cd build
  - cmake -DETISS_BUILD_MANUAL_DOC=ON ..
  - make doc

# Generate and deploy documentation
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build/doc/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master
