sudo: false

dist: bionic

language:
    - c++

# Blacklist
branches:
  only:
    - master

# Install dependencies
addons:
  apt:
    packages:
      - g++
      - doxygen
      - graphviz

before_install:
  - sudo apt-get update
  - sudo apt-get install libboost-system-dev
  - sudo apt-get install libboost-filesystem-dev
  - sudo apt-get install libtinfo-dev
  - sudo apt-get install zlib1g-dev
  #- sudo apt-get install gdbserver
  #- sudo apt-get install build-essential git
  #- sudo apt install clang

install:
  - 
  - mkdir -p ${TRAVIS_BUILD_DIR}/deps/cmake #directory for Cmake version 3.16.2
  - mkdir -p ${TRAVIS_BUILD_DIR}/deps/toolchain #directly for Riscv64 toolchain
  - mkdir -p ${TRAVIS_BUILD_DIR}/deps/LLVM #directory for LLVM 
  - wget https://cmake.org/files/v3.16/cmake-3.16.2-Linux-x86_64.sh # getting Cmake version 3.16.2
  - sh cmake-3.16.2-Linux-x86_64.sh --prefix=${TRAVIS_BUILD_DIR}/deps/cmake --exclude-subdir #save cmake package into directory
  - wget https://static.dev.sifive.com/dev-tools/riscv64-unknown-elf-gcc-8.3.0-2019.08.0-x86_64-linux-ubuntu14.tar.gz #Install sifive riscv64 package
  - tar -zxf riscv64-unknown-elf-gcc-8.3.0-2019.08.0-x86_64-linux-ubuntu14.tar.gz --directory ${TRAVIS_BUILD_DIR}/deps/toolchain #extract file to directory
  - travis_retry wget https://releases.llvm.org/7.0.1/clang+llvm-7.0.1-x86_64-linux-gnu-ubuntu-18.04.tar.xz #install LLVM 7.0.1
  - tar -xf clang+llvm-7.0.1-x86_64-linux-gnu-ubuntu-18.04.tar.xz --directory ${TRAVIS_BUILD_DIR}/deps/LLVM #extract LLVM to directory
  - PATH=${TRAVIS_BUILD_DIR}/deps/cmake:${TRAVIS_BUILD_DIR}/deps/cmake/bin:${TRAVIS_BUILD_DIR}/deps/toolchain:$PATH #hiding old version of Cmake

  
# Build ETISS your code e.g. by calling make
before_script:
  - mkdir build_dir && cd build_dir
  - cmake -DLLVM_DIR=${TRAVIS_BUILD_DIR}/deps/LLVM/clang+llvm-7.0.1-x86_64-linux-gnu-ubuntu-18.04/lib/cmake/llvm -DCMAKE_BUILD_TYPE=Release -DETISS_BUILD_MANUAL_DOC=ON -DCMAKE_INSTALL_PREFIX:PATH=`pwd`/installed ..
  - make
  - make doc
  - make install

script:
  - cd ${TRAVIS_BUILD_DIR}/build_dir/installed/examples/SW/riscv
  - mkdir build
  - cd build
  - cmake -DRISCV_ELF_GCC_PREFIX=${TRAVIS_BUILD_DIR}/deps/toolchain/riscv64-unknown-elf-gcc-8.3.0-2019.08.0-x86_64-linux-ubuntu14 -DRISCV_ELF_GCC_BASENAME=riscv64-unknown-elf ..
  - make
  - cd ${TRAVIS_BUILD_DIR}/build_dir/installed/examples/SW/riscv_cpp
  - mkdir build
  - cd build
  - cmake -DRISCV_ELF_GCC_PREFIX=${TRAVIS_BUILD_DIR}/deps/toolchain/riscv64-unknown-elf-gcc-8.3.0-2019.08.0-x86_64-linux-ubuntu14 -DRISCV_ELF_GCC_BASENAME=riscv64-unknown-elf ..
  - make 
  - cd ${TRAVIS_BUILD_DIR}/build_dir/installed/examples/bare_etiss_processor
  - mkdir build && cd build
  - cmake ..
  - make
  - cd ..
  - ./run_helper.sh ${TRAVIS_BUILD_DIR}/build_dir/installed/examples/SW/riscv/build/riscv_example 
  - ./run_helper.sh ${TRAVIS_BUILD_DIR}/build_dir/installed/examples/SW/riscv_cpp/build/riscv_example 
   
 

# Generate and deploy documentation
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build_dir/doc/html
  github_token: $GITHUB_TOKEN
  on:
    branch: master

